apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-service
  namespace: backend
  labels:
    app.kubernetes.io/name: approval-service
    app.kubernetes.io/instance: approval-service-instance
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: approval-service-instance
      app.kubernetes.io/name: approval-service
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: approval-service-instance
        app.kubernetes.io/name: approval-service
    spec:
      containers:
        - name: approval-service
          image: "aitdevops.azurecr.io/approval-service:latest"  # Uses the 'latest' tag
          ports:
            - containerPort: 3003
          livenessProbe:
            httpGet:
              path: /
              port: 3003
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3003
            initialDelaySeconds: 30
            timeoutSeconds: 5
