apiVersion: v1
kind: Service
metadata:
  name: approval-service
  namespace: backend
  labels:
    app.kubernetes.io/name: approval-service
    app.kubernetes.io/instance: approval-service-instance
    app.kubernetes.io/version: "1.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: approval-service-instance
    app.kubernetes.io/name: approval-service