apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-argocd
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rajeevkoppisetti21@gmail.com  # "Replace with your email"
    privateKeySecretRef:
      name: letsencrypt-argocd-prod
    solvers:
    - http01:
        ingress:
          class: nginx
