apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-backend
    cert-manager.io/acme-challenge-type: http01
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - auth.aitdevops.com
      - user.aitdevops.com
      - approval.aitdevops.com
    secretName: backend-tls
  rules:
  - host: auth.aitdevops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
  - host: user.aitdevops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80
  - host: approval.aitdevops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: approval-service
            port:
              number: 80
