apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-backend
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - auth.aitdevops.com
    - user.aitdevops.com
    - approval.aitdevops.com
    secretName: backend-tls
  rules:
  - host: auth.aitdevops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth-service-app-auth-service
            port:
              number: 3001
  - host: user.aitdevops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-service-app-user-service
            port:
              number: 3002
  - host: approval.aitdevops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: approval-service-app-approval-service
            port:
              number: 3003
