apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-frontend
spec:
  tls:
  - hosts:
    - aitdevops.com
    secretName: frontend-tls
  rules:
  - host: aitdevops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aitdevops-site
            port:
              number: 80
