apiVersion: apps/v1
kind: Deployment
metadata:
  name: aitdevops-site
  namespace: frontend
  labels:
    app.kubernetes.io/name: aitdevops-site
    app.kubernetes.io/instance: aitdevops-site-instance
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: aitdevops-site-instance
      app.kubernetes.io/name: aitdevops-site
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: aitdevops-site-instance
        app.kubernetes.io/name: aitdevops-site
    spec:
      containers:
        - name: aitdevops-site
          image: "us-central1-docker.pkg.dev/aitdevops8/aitdevops-gke/frontend:36e6f4dbb759694aad9de910d92fc545f03f99a8"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
