apiVersion: apps/v1
kind: Deployment
metadata:
  name: aitdevops-site
  labels:
    app.kubernetes.io/name: aitdevops-site
    app.kubernetes.io/instance: aitdevops-site-instance
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: aitdevops-site-instance
      app.kubernetes.io/name: aitdevops-site
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: aitdevops-site-instance
        app.kubernetes.io/name: aitdevops-site
    spec:
      containers:
        - name: aitdevops-site
<<<<<<< HEAD
          image: "us-central1-docker.pkg.dev/aitdevops8/aitdevops-gke/frontend:06e49ff7b1f817f9071645311759391717b23512"
=======
          image: "us-central1-docker.pkg.dev/aitdevops8/aitdevops-gke/frontend:06e49ff7b1f817f9071645311759391717b23512"
>>>>>>> 3c466fe0cbdf86723263682ec4613ce8cd3793d9
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
