apiVersion: apps/v1
kind: Deployment
metadata:
  name: aitdevops-site
  namespace: frontend
  labels:
    app.kubernetes.io/name: aitdevops-site
    app.kubernetes.io/instance: aitdevops-site-instance
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: aitdevops-site-instance
      app.kubernetes.io/name: aitdevops-site
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: aitdevops-site-instance
        app.kubernetes.io/name: aitdevops-site
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - aitdevops-site
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: k8s-service-account
      containers:
        - name: aitdevops-site
          image: "us-central1-docker.pkg.dev/devops-projects-426703/aitdevops-gke/frontend:f177a967e7a48250d94fa6c4d95089cc7e0b3926"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
