apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/aitdevops/argocd.git'
        revision: main
        directories:
          - path: 'argo-cd/argo-apps/*'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/aitdevops/argocd.git'
        targetRevision: main
        path: 'argo-cd/argo-apps/{{path.basename}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
