apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aitdevops/argocd.git'
    targetRevision: main
    path: charts/auth-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
