apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: backend
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/instance: auth-service-instance
    app.kubernetes.io/version: "1.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: auth-service-instance
    app.kubernetes.io/name: auth-service
