apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aitdevops-site.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: tls-secret  # Cert-Manager will create this secret
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "aitdevops-site.fullname" . }}
                port:
                  number: 80
