apiVersion: v1
kind: Service
metadata:
  name: {{ include "aitdevops-site.fullname" . }}
  labels:
    {{- include "aitdevops-site.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
