apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "argocd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "argocd.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: argocd-server
          image: argoproj/argocd:{{ .Values.global.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.server.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.server.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          # resources:
          #   limits:
          #     cpu: 250m
          #     memory: 256Mi
          #   requests:
          #     cpu: 250m
          #     memory: 256Mi
