apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "argocd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
