apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: backend
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/instance: auth-service-instance
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: auth-service-instance
      app.kubernetes.io/name: auth-service
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: auth-service-instance
        app.kubernetes.io/name: auth-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "role"
                    operator: "In"
                    values:
                      - "backend-pool"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - auth-service
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: k8s-service-account
      containers:
        - name: auth-service
          image: "us-central1-docker.pkg.dev/devops-projects-426703/aitdevops-gke/auth-service:bb7f250458891dac5e981f607d0c42ab6546f16c-auth"
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 30
            timeoutSeconds: 5
