apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: backend
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/instance: user-service-instance
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: user-service-instance
      app.kubernetes.io/name: user-service
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: user-service-instance
        app.kubernetes.io/name: user-service
    spec:
      containers:
        - name: user-service
          image: "us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.CLUSTER_NAME }}/user-service:6a2b4d9fa9af817a7e851774603153f9f961f22e-user"
          ports:
            - containerPort: 3002
          livenessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 30
            timeoutSeconds: 5