apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aitdevops/argocd.git'
    targetRevision: main
    path: 'elk'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elk-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    directory:
      recurse: true
  destination:
    namespace: elk-stack
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
